apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: nodepool
spec:
  template:
    spec:
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: nodepool
