apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: nodepool
  namespace: default
spec:
  mode: System
  osDiskSizeGB: 30
  sku: ${AZURE_NODE_MACHINE_TYPE}
