kind: Cluster
apiVersion: cluster.x-k8s.io/v1beta1
metadata:
  name: "${CLUSTER_NAME}"
  namespace: default
spec:
  clusterNetwork:
    services:
      cidrBlocks: [ "192.168.0.0/16" ]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureCluster
    name: "${CLUSTER_NAME}"
