apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: nodepool
spec:
  clusterName: ${CLUSTER_NAME}
  replicas: ${WORKER_MACHINE_COUNT}
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: ${CLUSTER_NAME}
      version: ${KUBERNETES_VERSION}
