apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: "${CLUSTER_NAME}-kct"
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          name: '{{ ds.meta_data["local_hostname"] }}'
          kubeletExtraArgs:
            cloud-provider: azure
            cloud-config: /etc/kubernetes/azure.json
            azure-container-registry-config: /etc/kubernetes/azure.json
      files:
        - contentFrom:
            secret:
              name: ${CLUSTER_NAME}-md-0-azure-json
              key: worker-node-azure.json
          owner: root:root
          path: /etc/kubernetes/azure.json
          permissions: "0644"
