name: Run CI E2E
on:
  pull_request_target:
    types: [ labeled ]
    branches:
      - main
  workflow_dispatch:
    inputs:
      from_branch:
        description: 'Which branch to run from? (default: main)'
        required: false
        default: 'main'
jobs:
  ci-e2e:
    if: contains(github.event.pull_request.labels.*.name, 'safe to test') || github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: install sonobuoy
        run: |
          sudo curl -fsSL https://github.com/vmware-tanzu/sonobuoy/releases/download/v0.54.0/sonobuoy_0.54.0_linux_amd64.tar.gz -o sonobuoy_0.54.0_linux_amd64.tar.gz
          sudo tar -xvf ./sonobuoy_0.54.0_linux_amd64.tar.gz
          sudo chmod +x ./sonobuoy
          sudo mv ./sonobuoy /usr/local/bin/sonobuoy
          sudo rm ./sonobuoy_0.54.0_linux_amd64.tar.gz
      - name: checkout perf-tests
        uses: actions/checkout@v2
        with:
          repository: kubernetes/perf-tests
          path: perf-tests
          ref: master
      - name: build clusterloader2 binary
        run: |
          go build -o cmd/clusterloader cmd/clusterloader.go
        working-directory: perf-tests/clusterloader2
      - name: run E2E
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          CL2_NS_COUNT: 15
          CL2_CLEANUP: 0
          CL2_REPEATS: 4
          CL2_POD_START_TIMEOUT_MINS: 20
          CL2_PODS_PER_NODE: 20
          CL2_TARGET_POD_CHURN: 50
          CL2_PODS_PER_DEPLOYMENT: 64
        run: scripts/ci-e2e.sh
