name: Run CI E2E
on:
  pull_request_target:
    types: [ labeled ]
    branches:
      - main
  workflow_dispatch:
    inputs:
      from_branch:
        description: 'Which branch to run from? (default: main)'
        required: false
        default: 'main'
jobs:
  ci-e2e:
    if: contains(github.event.pull_request.labels.*.name, 'safe to test') || github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: install sonobuoy
        run: |
          sudo curl -fsSL https://github.com/vmware-tanzu/sonobuoy/releases/download/v0.54.0/sonobuoy_0.54.0_linux_amd64.tar.gz -o sonobuoy_0.54.0_linux_amd64.tar.gz
          sudo tar -xvf ./sonobuoy_0.54.0_linux_amd64.tar.gz
          sudo chmod +x ./sonobuoy
          sudo mv ./sonobuoy /usr/local/bin/sonobuoy
          sudo rm ./sonobuoy_0.54.0_linux_amd64.tar.gz
      - name: checkout perf-tests
        uses: actions/checkout@v2
        with:
          repository: kubernetes/perf-tests
          path: perf-tests
          ref: release-1.20
      - name: build clusterloader2 binary
        path: perf-tests
        run: |
          go build cmd/clusterloader.go -o ./clusterloader
      - name: run E2E
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        run: scripts/ci-e2e.sh
