name: Run CI E2E
on:
  pull_request_target:
    types: [ labeled ]
    branches:
      - main
jobs:
  ci-e2e:
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: install sonobuoy
        run: |
          sudo curl -fsSL https://github.com/vmware-tanzu/sonobuoy/releases/download/v0.54.0/sonobuoy_0.54.0_linux_amd64.tar.gz -o sonobuoy_0.54.0_linux_amd64.tar.gz
          sudo tar -xvf ./sonobuoy_0.54.0_linux_amd64.tar.gz
          sudo chmod +x ./sonobuoy
          sudo mv ./sonobuoy /usr/local/bin/sonobuoy
          sudo rm ./sonobuoy_0.54.0_linux_amd64.tar.gz
      - name: run E2E
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        run: scripts/ci-e2e.sh
